DB_HOST: localhost
DB_NAME: scoach
DB_PASSWORD: mypassword
DB_PORT: 5432
DB_USER: postgres
MINIO_ACCESS_KEY: minio-access-key
MINIO_SECRET_KEY: minio-secret-key
MINIO_BUCKET: minio-bucket
MINIO_ENDPOINT: minio.example.com
MINIO_ENDPOINT_PORT: 443
MINIO_ENDPOINT_SCHEMA: https
SLURM_PARTITION: "debug"
SLURM_CORES_PER_JOB: 1
SLURM_MEMORY_PER_JOB: "1G"
SLURM_WORKER_NAME: "worker_name"
SLURM_JOB_EXCLUSIVE: false
SLURM_MAX_WORKERS: 1
DJANGO_SETTINGS_MODE: prod
