from enum import Enum
from pathlib import Path


class constants (Enum):
    """
    Constants for the application
    """
    # Redis
    REDIS_HOST_ENV = 'REDIS_HOST'
    REDIS_HOST_ENV_DEFAULT = 'localhost'
    REDIS_PORT_ENV = 'REDIS_PORT'
    REDIS_PORT_ENV_DEFAULT = 6379
    REDIS_DB_ENV = 'REDIS_DB'
    REDIS_DB_ENV_DEFAULT = 0
    REDIS_PASSWORD_ENV = 'REDIS_PASSWORD'
    REDIS_PASSWORD_ENV_DEFAULT = None
    REDIS_QUEUE_NAME_ENV = 'REDIS_QUEUE_NAME'
    REDIS_QUEUE_NAME_ENV_DEFAULT = None

    # Database
    DB_CONNECTION_STRING_ENV = 'DB_CONNECTION_STRING'
    DB_CONNECTION_STRING_ENV_DEFAULT = None

    # SLURM
    SLURM_PARTITION_ENV = 'SLURM_PARTITION'
    SLURM_PARTITION_ENV_DEFAULT = None
    SLURM_CORES_PER_JOB_ENV = 'SLURM_CORES_PER_JOB'
    SLURM_CORES_PER_JOB_ENV_DEFAULT = 1
    SLURM_MEMORY_PER_JOB_ENV = 'SLURM_MEMORY_PER_JOB'
    SLURM_MEMORY_PER_JOB_ENV_DEFAULT = '1G'
    SLURM_WORKER_NAME_ENV = 'SLURM_WORKER_NAME'
    SLURM_WORKER_NAME_ENV_DEFAULT = None
    SLURM_JOB_EXCLUSIVE_ENV = 'SLURM_JOB_EXCLUSIVE'
    SLURM_JOB_EXCLUSIVE_ENV_DEFAULT = False
    SLURM_MAX_WORKERS_ENV = 'SLURM_MAX_WORKERS'
    SLURM_MAX_WORKERS_ENV_DEFAULT = 1

    # MinIO
    MINIO_ENDPOINT_ENV = 'MINIO_ENDPOINT'
    MINIO_ENDPOINT_ENV_DEFAULT = None
    MINIO_ACCESS_KEY_ENV = 'MINIO_ACCESS_KEY'
    MINIO_ACCESS_KEY_ENV_DEFAULT = None
    MINIO_SECRET_KEY_ENV = 'MINIO_SECRET_KEY'
    MINIO_SECRET_KEY_ENV_DEFAULT = None
    MINIO_BUCKET_ENV = 'MINIO_BUCKET'
    MINIO_BUCKET_ENV_DEFAULT = None
    WEIGHTS_PATH_PREFIX = 'weights/'
    SCRIPTS_PATH_PREFIX = "scripts/"

    # Dask scheduler
    DASK_DEFAULT_WORKERS = 0

    # Coach
    COACH_DEFAULT_CONFIG_PATH = Path.home() / '.coach/config.yaml'
